name: Scoop Manifest Validation

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate manifests ($\{{ matrix.shell }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        shell: [powershell, pwsh]
    defaults:
      run:
        shell: $\{{ matrix.shell }}

    steps:
      - name: Checkout Bucket
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
          path: my_bucket

      - name: Checkout Scoop
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core

      - name: Install test dependencies
        uses: potatoqualitee/psmodulecache@9e4b63833c22c1768d648e115a9c849afdda22a5 # v6.3
        with:
          modules-to-cache: BuildHelpers, Pester
          shell: $\{{ matrix.shell }}

      - name: Run official Scoop bucket tests
        env:
          SCOOP_HOME: $\{{ github.workspace }}\\scoop_core
        run: |
          .\\my_bucket\\bin\\test.ps1

      - name: Validate checkver for every manifest
        env:
          SCOOP_HOME: $\{{ github.workspace }}\\scoop_core
        run: |
          .\\scoop_core\\bin\\checkver.ps1 -Dir .\\my_bucket\\bucket -ThrowError
